import { slide } from '../../src/options.jsx';
import { SHOWCASE_DEV_ADJUSTMENTS, SHOWCASE_TEXT_OVERRIDES } from './showcase-copy-overrides.js';

export default {
  style: 'swiss',
  theme: process.env.GUIZANG_THEME || 'dark',
  fontSet: process.env.GUIZANG_FONT || 'cnReport',
  title: '大师的AI小灶-PPT Skill',
  text: SHOWCASE_TEXT_OVERRIDES,
  developerAdjustments: SHOWCASE_DEV_ADJUSTMENTS,
  slides: [
    slide('bt01'),
    slide('bt02'),
    slide('bt03'),
    slide('bt04'),
    slide('bt05'),
    slide('bt06'),
    slide('bt07'),
    slide('bt08'),
    slide('bt09'),
    slide('bt10'),
    slide('bt11'),
    slide('bt12'),
    slide('rp01'),
    slide('rp02'),
    slide('rp03'),
    slide('rp04'),
    slide('rp08'),
    slide('rp09'),
    slide('rp10'),
    slide('rp11'),
    slide('rp13'),
    slide('rp14'),
    slide('rp15'),
    slide('rp16'),
    slide('xhs01'),
    slide('xhs02'),
    slide('xhs04'),
    slide('xhs12'),
    slide('xhs15'),
    slide('xhs17'),
    slide('xhs18'),
    slide('xhs19'),
    slide('xhs22'),
    slide('xhs25'),
    slide('xhs2_01'),
    slide('xhs2_02'),
    slide('xhs2_03'),
    slide('xhs2_04'),
    slide('xhs2_05'),
    slide('xhs2_11'),
    slide('xhs2_15'),
    slide('xhs2_33'),
    slide('xhs2_34'),
    slide('xhs3_01'),
    slide('xhs3_02'),
    slide('xhs3_03'),
    slide('xhs3_04'),
    slide('xhs3_05'),
    slide('xhs3_06'),
    slide('xhs3_07'),
    slide('xhs3_08'),
    slide('xhs3_09'),
    slide('xhs3_10'),
    slide('xhs3_11'),
    slide('xhs3_12'),
    slide('xhs3_13'),
    slide('xhs3_14'),
    slide('xhs3_15'),
    slide('xhs3_16'),
    slide('xhs3_17'),
    slide('xhs3_18'),
    slide('xhs3_19'),
    slide('xhs3_20'),
    slide('xhs3_21'),
    slide('xhs3_22'),
    slide('xhs3_23'),
    slide('xhs3_24'),
    slide('xhs3_25'),
    slide('style1_01'),
    slide('style1_02'),
    slide('style1_03'),
    slide('style1_04'),
    slide('style1_05'),
    slide('style1_06'),
    slide('style2_01'),
    slide('style2_02'),
    slide('style2_03'),
    slide('style2_04'),
    slide('style2_05'),
    slide('style2_06'),
  ],
};
